steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'VELOCITY_JAR_URL=${_VELOCITY_JAR_URL}'
  - '-t'
  - 'gcr.io/possible-surf-250517/velocity'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/possible-surf-250517/velocity']
